"""The public-metadata guard covers pull request titles and descriptions from the Actions event payload."""
from __future__ import annotations

import importlib.util
import json
import os

spec = importlib.util.spec_from_file_location(
    "check", os.path.join(os.path.dirname(__file__), "..", "scripts", "check_public_metadata.py"))
check = importlib.util.module_from_spec(spec)
spec.loader.exec_module(check)

PRIVATE = "https://claude.ai/code/" + "session_" + "0123456789"


def _event(tmp_path, title, body):
    path = tmp_path / "event.json"
    path.write_text(json.dumps({"pull_request": {"number": 7, "title": title, "body": body}}))
    return str(path)


def test_links_in_a_pull_request_description_or_title_are_reported_without_the_url(tmp_path):
    found = check.pull_request_findings(_event(tmp_path, "Fix", f"Summary\n\n---\n_Generated by [x]({PRIVATE})_"))
    assert found == ["pull request #7 description:4: private session link"]
    assert check.pull_request_findings(_event(tmp_path, f"See {PRIVATE}", "")) == [
        "pull request #7 title:1: private session link"]
    assert all(PRIVATE not in line for line in found)


def test_clean_or_absent_pull_request_passes(tmp_path):
    assert check.pull_request_findings(_event(tmp_path, "Fix", "https://claude.ai/code is fine")) == []
    assert check.pull_request_findings(_event(tmp_path, "Fix", None)) == []
    assert check.pull_request_findings("") == []
    push = tmp_path / "push.json"
    push.write_text(json.dumps({"before": "0" * 40}))
    assert check.pull_request_findings(str(push)) == []


def test_live_pull_request_copy_wins_over_the_frozen_event(tmp_path):
    event = _event(tmp_path, "Fix", f"footer {PRIVATE}")
    live = tmp_path / "pull-request.json"
    live.write_text(json.dumps({"number": 7, "title": "Fix", "body": "footer removed"}))
    assert check.pull_request_findings(event) != []
    assert check.pull_request_findings(event, str(live)) == []
    live.write_text(json.dumps({"number": 7, "title": "Fix", "body": f"still {PRIVATE}"}))
    assert check.pull_request_findings(event, str(live)) == ["pull request #7 description:1: private session link"]
