"""Experimental JIT cognitive execution optimizer."""

from .authority import (
    AuthorityEvidenceError,
    AuthorityGateEvidence,
    apply_faar_authority,
    normalize_faar_authority_decision,
)
from .cache import CacheEnvelope, RiskAwareResultCache
from .cost_calibration import CostCalibrationPolicy, CostCalibrationSnapshot, PCFCostCalibrator
from .deterministic import (
    DeterministicArtifact,
    DeterministicCompileError,
    DeterministicExecutionError,
    DeterministicPolicy,
    compile_deterministic_artifact,
    execute_deterministic_artifact,
)
from .deterministic_canary import (
    DeterministicCanaryEvidence,
    DeterministicCanaryPolicy,
    activate_deterministic_candidate,
    evaluate_deterministic_canary,
    rollback_failed_deterministic_canary,
    start_deterministic_canary,
)
from .deterministic_monitor import (
    DeterministicHealthEvidence,
    DeterministicMonitorPolicy,
    demote_unhealthy_deterministic_active,
    evaluate_deterministic_active_health,
)
from .deterministic_pipeline import (
    DeterministicBuildEvidence,
    DeterministicBuildPolicy,
    DeterministicCandidateBuild,
    DeterministicPipelineError,
    DeterministicShadowEvaluation,
    DeterministicValidationExample,
    evaluate_deterministic_shadow,
    execute_verified_deterministic_artifact,
    make_deterministic_shadow_target,
    mark_deterministic_candidate_eligible,
    prepare_deterministic_candidate,
    register_deterministic_shadow_candidate,
    verify_deterministic_artifact,
)
from .deterministic_synthesis import (
    SYNTHESIS_VERSION,
    DeterministicSynthesisError,
    DeterministicSynthesisEvidence,
    DeterministicSynthesisPolicy,
    DeterministicSynthesisResult,
    synthesize_and_prepare_deterministic_candidate,
    synthesize_deterministic_expression,
)
from .fingerprint import FingerprintAudit, FingerprintAuditSummary, FingerprintObservation, TaskSignature
from .hotpath import CompileEconomics, CompileEligibility, HotPathDetector, HotPathStats
from .jev_benchmark import (
    JevBenchmarkCase,
    JevBenchmarkObservation,
    JevBenchmarkSummary,
    default_jev_benchmark_cases,
    run_jev_benchmark,
)
from .jev_openrouter import (
    DEFAULT_JEV_MODEL,
    DEFAULT_OPENROUTER_DECISIONS_URL,
    JevOpenRouterError,
    JevRouteAdvice,
    JevRouteBenchmarkStats,
    JevUsage,
    OpenRouterJevClient,
    annotate_candidates_with_jev,
)
from .jev_selective import (
    JevSelectiveEvidence,
    JevSelectivePolicy,
    evaluate_jev_selective_evidence,
    wilson_lower_bound,
)
from .optimizer import JITOptimizer, NoAdmissibleRoute
from .pcf_cost import (
    PCFInputCostEstimate,
    apply_pcf_input_cost,
    estimate_pcf_input_cost,
    make_pcf_metered_shadow_runner,
)
from .pcf_reconcile import (
    PCFInputCostReconciliation,
    PCFReconciliationStats,
    apply_pcf_reconciled_input_cost,
    make_pcf_reconciled_shadow_runner,
    reconcile_pcf_input_cost,
)
from .promotion import PromotionDecision, PromotionEvaluator, PromotionEvidence, PromotionPolicy
from .registry import (
    InvalidRouteTransition,
    RegisteredRoute,
    RouteRegistry,
    RouteState,
    RouteTransition,
    StaleRouteGeneration,
)
from .shadow import (
    ReplayRouteStats,
    ShadowAssessment,
    ShadowExecutor,
    ShadowObservation,
    ShadowRequest,
    ShadowResult,
    ShadowRun,
    ShadowTarget,
    TraceReplaySummary,
    TraceReplayer,
)
from .sqlite_registry import RegistryStorageError, SQLiteRouteRegistry
from .types import CandidateScore, ExecutionPrimitive, OptimizerPolicy, RouteCandidate, RouteDecision

__all__ = [
    "AuthorityEvidenceError",
    "AuthorityGateEvidence",
    "CacheEnvelope",
    "CandidateScore",
    "CompileEconomics",
    "CompileEligibility",
    "CostCalibrationPolicy",
    "CostCalibrationSnapshot",
    "DEFAULT_JEV_MODEL",
    "DEFAULT_OPENROUTER_DECISIONS_URL",
    "DeterministicArtifact",
    "DeterministicBuildEvidence",
    "DeterministicBuildPolicy",
    "DeterministicCanaryEvidence",
    "DeterministicCanaryPolicy",
    "DeterministicCandidateBuild",
    "DeterministicCompileError",
    "DeterministicExecutionError",
    "DeterministicHealthEvidence",
    "DeterministicMonitorPolicy",
    "DeterministicPipelineError",
    "DeterministicPolicy",
    "DeterministicShadowEvaluation",
    "DeterministicSynthesisError",
    "DeterministicSynthesisEvidence",
    "DeterministicSynthesisPolicy",
    "DeterministicSynthesisResult",
    "DeterministicValidationExample",
    "ExecutionPrimitive",
    "FingerprintAudit",
    "FingerprintAuditSummary",
    "FingerprintObservation",
    "HotPathDetector",
    "HotPathStats",
    "InvalidRouteTransition",
    "JITOptimizer",
    "JevBenchmarkCase",
    "JevBenchmarkObservation",
    "JevBenchmarkSummary",
    "JevOpenRouterError",
    "JevRouteAdvice",
    "JevRouteBenchmarkStats",
    "JevSelectiveEvidence",
    "JevSelectivePolicy",
    "JevUsage",
    "NoAdmissibleRoute",
    "OpenRouterJevClient",
    "OptimizerPolicy",
    "PCFCostCalibrator",
    "PCFInputCostEstimate",
    "PCFInputCostReconciliation",
    "PCFReconciliationStats",
    "PromotionDecision",
    "PromotionEvaluator",
    "PromotionEvidence",
    "PromotionPolicy",
    "RegisteredRoute",
    "RegistryStorageError",
    "ReplayRouteStats",
    "RiskAwareResultCache",
    "RouteCandidate",
    "RouteDecision",
    "RouteRegistry",
    "RouteState",
    "RouteTransition",
    "SYNTHESIS_VERSION",
    "SQLiteRouteRegistry",
    "ShadowAssessment",
    "ShadowExecutor",
    "ShadowObservation",
    "ShadowRequest",
    "ShadowResult",
    "ShadowRun",
    "ShadowTarget",
    "StaleRouteGeneration",
    "TaskSignature",
    "TraceReplaySummary",
    "TraceReplayer",
    "activate_deterministic_candidate",
    "annotate_candidates_with_jev",
    "apply_faar_authority",
    "apply_pcf_input_cost",
    "apply_pcf_reconciled_input_cost",
    "compile_deterministic_artifact",
    "default_jev_benchmark_cases",
    "demote_unhealthy_deterministic_active",
    "estimate_pcf_input_cost",
    "evaluate_deterministic_active_health",
    "evaluate_deterministic_canary",
    "evaluate_deterministic_shadow",
    "evaluate_jev_selective_evidence",
    "execute_deterministic_artifact",
    "execute_verified_deterministic_artifact",
    "make_deterministic_shadow_target",
    "make_pcf_metered_shadow_runner",
    "make_pcf_reconciled_shadow_runner",
    "mark_deterministic_candidate_eligible",
    "normalize_faar_authority_decision",
    "prepare_deterministic_candidate",
    "reconcile_pcf_input_cost",
    "register_deterministic_shadow_candidate",
    "rollback_failed_deterministic_canary",
    "run_jev_benchmark",
    "start_deterministic_canary",
    "synthesize_and_prepare_deterministic_candidate",
    "synthesize_deterministic_expression",
    "verify_deterministic_artifact",
    "wilson_lower_bound",
]
